baseURL: "https://git-trending-rank.github.io/"
title: "Git Trending Rank"
googleAnalytics: "G-Q218PF1C3Y"
publishDir: "docs"
author: Young.Wang
language: zh-CN
timezone: 'Asia/Shanghai'

markup:
  goldmark:
    extensions:
      typographer: false
    renderer:
      unsafe: true

date_format: YYYY-MM-DD
time_format: HH:mm:ss
updated_option: data

module:
  hugoVersion:
    extended: true
    min: "0.157.0"
  imports:
    - path: github.com/CaiJimmy/hugo-theme-stack/v4

params:
  mainSections:
    - post

  colorScheme:
    toggle: true
    default: auto

  sidebar:
    compact: false
    avatar: "https://avatars.githubusercontent.com/u/15307132?v=4"

  dateFormat:
    published: "2006-01-02 15:04:05"
    lastUpdated: "2006-01-02 15:04:05"

  article:
    toc: true

  comments:
    enabled: true
    provider: gitalk
    gitalk:
      owner: git-trending-rank
      admin: git-trending-rank
      repo: rank-gitalk
      clientID: Ov23liLkC9rn7DCWrOFm
      clientSecret: 8de1406fe7f558f96eccaf1d3e1ff0d821af981c
      distractionFreeMode: true
      language: zh-CN

  widgets:
    homepage:
      - type: toc
    page: []
