name: Scheduled task

on:
  schedule:
    - cron: '55 1-23/2 * * *'
      branches:
        - main
  workflow_dispatch: # 手动触发
    branches:
      - main # workflow_dispatch 也可以限制分支。

jobs:
  generated_file_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.24.0' # 或者你需要的 Go 版本

      - name: Build Go project
        run: go build -o myapp # 替换 myapp 为你的可执行文件名

      - name: Run Go programs
        run: |
          ./myapp 

      - name: Configure Git
        run: |
          git config user.email "979238315@qq.com"
          git config user.name "actions cron"

      - name: Add and commit new files
        run: |
          current_time=$(date +"%Y-%m-%d %H:%M:%S")
          git add content/post/ 
          git commit -m "Add generated files - ${current_time}" || echo "No changes to commit"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GIT_TOKEN }}
          branch: main
          force: true

  deploy:
    runs-on: ubuntu-latest
    needs: generated_file_and_push
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true # 如果你需要 Hugo extended 版本，取消注释

      - name: download themes
        run: mkdir -p themes && git clone https://github.com/CaiJimmy/hugo-theme-stack.git themes/hugo-theme-stack

      - name: init mod
        run: hugo mod get && hugo mod tidy

      - name: Build site
        run: hugo --config ./config.yaml
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GIT_TOKEN }}
          publish_dir: ./docs